# Generated by Django 4.2.16 on 2024-11-26 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0274_alter_customer_locale_alter_event_currency_and_more'),
        ('pretix_midtrans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midtranstransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midtrans_transaction', to='pretixbase.order'),
        ),
    ]
